### ISSUE TITLE
Install fails due to cryptutils-paypal dependency

### ISSUE THREAD

**Issue by wateryoma** [krakenjs/memcookies#1]
Seems like a great lib, wanted to give it a try, but... Please fix

``` shell
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/cryptutils-paypal
npm ERR! 404 
npm ERR! 404  'cryptutils-paypal' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'memcookies'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by wateryoma** [comment]
Sorry, my bad, that way

``` shell
npm i https://github.com/krakenjs/memcookies.git -S
```

everything is ok

**Comment by sinhanurag** [comment]
I see we don't have the correct information in the npm registry for this package. Will fix it.

**Comment by mstuart** [comment]
Hmm, npm is still a mystery to me.  There's two 1.x versions, and when you `npm install`, it pulls in 0.x versions?  So weird.  Sorry @wateryoma never seen anything like this yet... trying to figure it out :)

**Comment by mstuart** [comment]
It might be fixed now?  I don't know what I did, but:

```
$ npm install memcookies
lol@1.0.0 /Users/marstuart/lol
└─┬ memcookies@1.0.2 
  ├── cookiejar@2.1.0 
  ├── on-headers@1.0.1 
  └── underscore@1.8.3 
```

/shrug

**Comment by wateryoma** [comment]
thanks,
one of teammate of yours, already solved similar issue here - https://github.com/krakenjs/jwt-csrf/issues/2

**Comment by wateryoma** [comment]
great! yes it's solved now, thanks again for really quick fix)

**Comment by mstuart** [comment]
Sorry for the trouble.  These were internal modules that we published publicly, so we had to remove the PayPal specific parts.  Hope its all ironed out now.  Pretty cool you have a use for memcookies, though.  Thanks!

**Comment by mstuart** [comment]
Let us know if you have any questions or issues w/ this.  Happy to help!
